import type { CctvCamera } from './types';
import { BULGARIA_FWCBG_CAMERAS } from './bulgaria-fwcbg.generated';
import { windy } from './windy';
import { filterHealthyBalkansCameras } from './balkans-filter';

/**
 * Curated cameras from non-free-webcambg sources (UAB/GKPP, Smart Burgas HLS, YouTube, meteo).
 * Combined with auto-generated free-webcambg catalog (~350 cameras, ~170 live rtsp.me).
 */
const BULGARIA_MANUAL: CctvCamera[] = [
  // ── UAB / KAMEPA traffic (not on free-webcambg) ──
  {
    id: 'bg-sofia-tsarigradsko-uab',
    lat: 42.662,
    lng: 23.376,
    name: 'Tsarigradsko Shose (UAB)',
    city: 'Sofia',
    country: 'Bulgaria',
    feed_url: 'https://cdn.uab.org/images/cctv/images/cctv/cctv_103/cctv.jpg',
    source: 'UAB / KAMEPA',
  },
  {
    id: 'bg-sofia-banishora',
    lat: 42.704,
    lng: 23.327,
    name: 'Banishora / Opalchenska',
    city: 'Sofia',
    country: 'Bulgaria',
    feed_url: 'https://meteo.chavo.biz/Camera_streem/live_snap.jpg',
    source: 'meteo.chavo.biz',
  },
  {
    id: 'bg-sofia-iztok',
    lat: 42.679,
    lng: 23.364,
    name: 'Iztok / Arena',
    city: 'Sofia',
    country: 'Bulgaria',
    feed_url: 'http://85.118.88.81:8000/jpg/image.jpg?resolution=1280x960',
    source: 'Private cam',
  },
  {
    id: 'bg-sofia-lagera',
    lat: 42.603,
    lng: 23.297,
    name: 'Lagera / Vitosha',
    city: 'Sofia',
    country: 'Bulgaria',
    feed_url: 'https://www.meteobrite.com/rest/image?stationId=4',
    source: 'MeteoBrite',
  },

  // ── GKPP / border (UAB + weather-webcam + YouTube) ──
  {
    id: 'bg-gkpp-kulata-1',
    lat: 41.395,
    lng: 23.361,
    name: 'GKPP Kulata – Promachon (BG)',
    city: 'Kulata',
    country: 'Bulgaria',
    feed_url: 'https://cdn.uab.org/images/cctv/images/cctv/cctv_01/cctv.jpg',
    external_url: 'https://weather-webcam.eu/kameri-ot-gkpp-kulata-promahon-sledete-trafika-na-grackata-granica/',
    source: 'UAB / GKPP',
  },
  {
    id: 'bg-gkpp-kulata-2',
    lat: 41.394,
    lng: 23.363,
    name: 'GKPP Kulata – Promachon (approach)',
    city: 'Kulata',
    country: 'Bulgaria',
    feed_url: 'https://cdn.uab.org/images/cctv/images/cctv/cctv_02/cctv.jpg',
    external_url: 'https://weather-webcam.eu/kameri-ot-gkpp-kulata-promahon-sledete-trafika-na-grackata-granica/',
    source: 'UAB / GKPP',
  },
  {
    id: 'bg-gkpp-kulata-3',
    lat: 41.396,
    lng: 23.359,
    name: 'GKPP Kulata – queue',
    city: 'Kulata',
    country: 'Bulgaria',
    feed_url: 'https://cdn.uab.org/images/cctv/images/cctv/cctv_114/cctv.jpg',
    external_url: 'https://weather-webcam.eu/kameri-ot-gkpp-kulata-promahon-sledete-trafika-na-grackata-granica/',
    source: 'UAB / GKPP',
  },
  {
    id: 'bg-gkpp-zlatograd',
    lat: 41.379,
    lng: 25.056,
    name: 'GKPP Zlatograd – Thermes (BG–GR)',
    city: 'Zlatograd',
    country: 'Bulgaria',
    feed_url: 'https://www.weather-webcam.eu/cams/gkpp-zlatograd.jpg',
    external_url: 'https://weather-webcam.eu/ueb-kamera-ot-gkpp-zlatograd-termes-zlatograd-ksanti/',
    source: 'weather-webcam.eu',
  },
  {
    id: 'bg-gkpp-ruse-1',
    lat: 43.845,
    lng: 25.974,
    name: 'GKPP Ruse – Giurgiu (Danube Bridge)',
    city: 'Ruse',
    country: 'Bulgaria',
    feed_url: 'https://weather-webcam.eu/cams/gkpp-ruse-gurgevo-webcam-kamera-na-jivo.jpg',
    source: 'weather-webcam.eu',
  },
  {
    id: 'bg-gkpp-ruse-2',
    lat: 43.844,
    lng: 25.976,
    name: 'GKPP Ruse – Giurgiu (lane 2)',
    city: 'Ruse',
    country: 'Bulgaria',
    feed_url: 'https://weather-webcam.eu/cams/gkpp-ruse-gurgevo-webcam-kamera-na-jivo2.jpg',
    source: 'weather-webcam.eu',
  },
  {
    id: 'bg-gkpp-ruse-3',
    lat: 43.846,
    lng: 25.978,
    name: 'GKPP Ruse – Giurgiu (lane 3)',
    city: 'Ruse',
    country: 'Bulgaria',
    feed_url: 'https://weather-webcam.eu/cams/gkpp-ruse-gurgevo-webcam-kamera-na-jivo3.jpg',
    source: 'weather-webcam.eu',
  },
  {
    id: 'bg-gkpp-ruse-4',
    lat: 43.743,
    lng: 26.097,
    name: 'GKPP Tutrakan – Oltenița',
    city: 'Tutrakan',
    country: 'Bulgaria',
    feed_url: 'https://weather-webcam.eu/cams/ruse-webcam-gkpp-kam-tutrakan.jpg',
    source: 'weather-webcam.eu',
  },
  {
    id: 'bg-gkpp-vrashka-1',
    lat: 43.858,
    lng: 22.448,
    name: 'GKPP Vrashka Chuka',
    city: 'Vrashka Chuka',
    country: 'Bulgaria',
    feed_url: 'https://home-solutions.bg/cams/chuka2.jpg',
    source: 'home-solutions.bg',
  },
  {
    id: 'bg-gkpp-vrashka-2',
    lat: 43.857,
    lng: 22.45,
    name: 'GKPP Vrashka Chuka (alt)',
    city: 'Vrashka Chuka',
    country: 'Bulgaria',
    feed_url: 'https://home-solutions.bg/cams/chuka1.jpg',
    source: 'home-solutions.bg',
  },
  {
    id: 'bg-gkpp-makaza-1',
    lat: 41.297,
    lng: 24.133,
    name: 'GKPP Makaza – Nymfea (cam 1)',
    city: 'Makaza',
    country: 'Bulgaria',
    stream_url: 'https://www.youtube.com/embed/pnr0lhrqRAc?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://weather-webcam.eu/ueb-kameri-ot-gkpp-makaza-nimfeya/',
    source: 'YouTube / GKPP',
  },
  {
    id: 'bg-gkpp-makaza-2',
    lat: 41.296,
    lng: 24.135,
    name: 'GKPP Makaza – Nymfea (cam 2)',
    city: 'Makaza',
    country: 'Bulgaria',
    stream_url: 'https://www.youtube.com/embed/YXN19ZEpIkc?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://weather-webcam.eu/ueb-kameri-ot-gkpp-makaza-nimfeya/',
    source: 'YouTube / GKPP',
  },
  {
    id: 'bg-gkpp-kalotina',
    lat: 42.995,
    lng: 22.878,
    name: 'GKPP Kalotina – Gradina',
    city: 'Kalotina',
    country: 'Bulgaria',
    external_url: 'https://weather-webcam.eu/kalotina-online-webcam-kgpp-granichen-punkt-bulgaria-sarbia-kamera/',
    source: 'weather-webcam.eu',
  },
  {
    id: 'bg-gkpp-gueshevo',
    lat: 42.148,
    lng: 22.535,
    name: 'GKPP Gyueshevo – Deve Bair',
    city: 'Gyueshevo',
    country: 'Bulgaria',
    external_url: 'https://weather-webcam.eu/gueshevo-online-webcam-kgpp-granichen-punkt-bulgaria-makedonia-kamera/',
    source: 'weather-webcam.eu',
  },
  {
    id: 'bg-gkpp-kapitan-andreevo',
    lat: 41.718,
    lng: 26.328,
    name: 'GKPP Kapitan Andreevo – Kapıkule',
    city: 'Svilengrad',
    country: 'Bulgaria',
    external_url: 'https://weather-webcam.eu/svilengrad-kapitan-andreevo-kapakule-odrin-live-kamera/',
    source: 'weather-webcam.eu',
  },
  {
    id: 'bg-gkpp-lesovo',
    lat: 41.968,
    lng: 26.385,
    name: 'GKPP Lesovo – Hamzabeyli',
    city: 'Lesovo',
    country: 'Bulgaria',
    external_url: 'https://weather-webcam.eu/lesovo-hamzabeyli-live-kamera-balgaria-turcia-granica-trafik-vremeto/',
    source: 'weather-webcam.eu',
  },
  {
    id: 'bg-gkpp-malko-tarnovo',
    lat: 41.407,
    lng: 27.518,
    name: 'GKPP Malko Tarnovo – Dereköy',
    city: 'Malko Tarnovo',
    country: 'Bulgaria',
    external_url: 'https://weather-webcam.eu/gkpp-malko-tarnovo-derekoi-live-kamera-balgaria-turcia-granica-trafik-vremeto/',
    source: 'weather-webcam.eu',
  },

  // ── NIMH / Smart Burgas HLS ──
  {
    id: 'bg-varna-treta-buna',
    lat: 43.214,
    lng: 27.923,
    name: 'NIMH Varna – Treta Buna (Sea Garden)',
    city: 'Varna',
    country: 'Bulgaria',
    ...windy('1613621604'),
    feed_url: 'https://home-solutions.bg/cams/varna-buna.jpg',
    external_url: 'https://weather-webcam.eu/varna-kamera-na-jivo-zaliv-treta-buna-black-sea/',
    source: 'NIMH / weather-webcam.eu',
  },
  {
    id: 'bg-burgas-center',
    lat: 42.497,
    lng: 27.47,
    name: 'Burgas Center (Smart Burgas HLS)',
    city: 'Burgas',
    country: 'Bulgaria',
    stream_url: 'https://pics.smartburgas.eu/m3u8/burgas_town_Center.m3u8',
    stream_type: 'hls',
    external_url: 'https://www.weather-webcam.eu/cams/burgas-centar.html',
    source: 'Smart Burgas',
  },
  {
    id: 'bg-burgas-sarafovo',
    lat: 42.65,
    lng: 27.7,
    name: 'Sarafovo – Black Sea Panorama',
    city: 'Burgas',
    country: 'Bulgaria',
    feed_url: 'https://www.weather-webcam.eu/cams/burgas-kvartal-sarafovo-na-jivo-kamera-panorama-cherno-more.jpg',
    source: 'weather-webcam.eu',
  },
  {
    id: 'bg-burgas-north-beach',
    lat: 42.51,
    lng: 27.474,
    name: 'North Beach / Windsurf',
    city: 'Burgas',
    country: 'Bulgaria',
    feed_url: 'http://5.104.177.125:8080/?action=snapshot',
    source: 'Private cam',
  },

  // ── Varna region (webcamera24.com — direct JPG/YouTube, no rtsp.me) ──
  {
    id: 'bg-varna-city-view-meter',
    lat: 43.212,
    lng: 27.909,
    name: 'Varna – City View (west)',
    city: 'Varna',
    country: 'Bulgaria',
    feed_url: 'https://meter.ac/gs/nodes/N118/snap.jpg',
    external_url: 'https://webcamera24.com/camera/bulgaria/8515-varna-west/',
    source: 'meter.ac / webcamera24',
  },
  {
    id: 'bg-varna-akchelar-meter',
    lat: 43.228,
    lng: 27.952,
    name: 'Akchelar – District View',
    city: 'Varna',
    country: 'Bulgaria',
    feed_url: 'https://meter.ac/gs/nodes/N125/snap.jpg',
    external_url: 'https://webcamera24.com/camera/bulgaria/8459-akchelar/',
    source: 'meter.ac / webcamera24',
  },
  {
    id: 'bg-varna-borovets-stringmeteo',
    lat: 43.229,
    lng: 27.965,
    name: 'Varna – Borovets District',
    city: 'Varna',
    country: 'Bulgaria',
    feed_url: 'https://www.stringmeteo.com/stations/varnaborovets/webcamimage.jpg',
    external_url: 'https://weather-webcam.eu/varna-borovec-na-jivo-kamera-online-vremeto-cherno-more/',
    source: 'stringmeteo / weather-webcam.eu',
  },
  {
    id: 'bg-varna-akchelar-stringmeteo',
    lat: 43.231,
    lng: 27.961,
    name: 'Varna – Akchelar District',
    city: 'Varna',
    country: 'Bulgaria',
    feed_url: 'https://www.stringmeteo.com/stations/varnaakchelar/webcamimage.jpg',
    external_url: 'https://weather-webcam.eu/varna-akchelar-live-camera-na-jivo/',
    source: 'stringmeteo / weather-webcam.eu',
  },
  {
    id: 'bg-byala-sea-panorama',
    lat: 42.872,
    lng: 27.888,
    name: 'Byala – Black Sea Panorama',
    city: 'Byala',
    country: 'Bulgaria',
    ...windy('1489252913'),
    feed_url: 'https://home-solutions.bg/cams/bqla.jpg',
    external_url: 'https://www.meteoblue.com/en/weather/webcams/varna_bulgaria_726050',
    source: 'Windy / home-solutions.bg',
  },
  {
    id: 'bg-goren-chiflik-live',
    lat: 43.009,
    lng: 27.629,
    name: 'Goren Chiflik – Street (live)',
    city: 'Goren Chiflik',
    country: 'Bulgaria',
    stream_url: 'https://www.youtube-nocookie.com/embed/Lv8iipE5hUY?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://webcamera24.com/camera/bulgaria/8524-blgaria-varna/',
    source: 'YouTube / webcamera24',
  },

  // ── Varna coast (Windy / meteoblue.com catalog) ──
  {
    id: 'bg-varna-windy',
    lat: 43.22,
    lng: 27.91,
    name: 'Varna – City',
    city: 'Varna',
    country: 'Bulgaria',
    ...windy('1761142086'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/varna_bulgaria_726050',
  },
  {
    id: 'bg-balchik-east-windy',
    lat: 43.428,
    lng: 28.172,
    name: 'Balchik – East',
    city: 'Balchik',
    country: 'Bulgaria',
    ...windy('1742250823'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/varna_bulgaria_726050',
  },
  {
    id: 'bg-balchik-windy',
    lat: 43.418,
    lng: 28.165,
    name: 'Balchik – Panorama',
    city: 'Balchik',
    country: 'Bulgaria',
    ...windy('1649538773'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/varna_bulgaria_726050',
  },
  {
    id: 'bg-bozhurets-windy',
    lat: 43.445,
    lng: 28.118,
    name: 'Bozhurets – South View',
    city: 'Kavarna',
    country: 'Bulgaria',
    ...windy('1581237139'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/varna_bulgaria_726050',
  },
  {
    id: 'bg-obzor-windy',
    lat: 42.817,
    lng: 27.882,
    name: 'Obzor – Beach',
    city: 'Obzor',
    country: 'Bulgaria',
    ...windy('1761142380'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/varna_bulgaria_726050',
  },
  {
    id: 'bg-obzor-morska-perla-windy',
    lat: 42.813,
    lng: 27.89,
    name: 'Obzor – Morska Perla',
    city: 'Obzor',
    country: 'Bulgaria',
    ...windy('1658480151'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/varna_bulgaria_726050',
  },
  {
    id: 'bg-tyulenovo-windy',
    lat: 43.582,
    lng: 28.588,
    name: 'Tyulenovo – East (North coast)',
    city: 'Tyulenovo',
    country: 'Bulgaria',
    ...windy('1741547452'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/golden-sands_bulgaria_6355004',
  },

  // ── Stara Planina & central BG (meteoblue/Windy) ──
  {
    id: 'bg-valevtsi-mazalat-windy',
    lat: 42.833,
    lng: 25.367,
    name: 'Valevtsi – Mazalat Hut',
    city: 'Stara Planina',
    country: 'Bulgaria',
    ...windy('1520935932'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/42.784N25.198E1177_Europe%2FSofia',
  },
  {
    id: 'bg-tazha-triglav-windy',
    lat: 42.722,
    lng: 25.448,
    name: 'Tazha – Triglav Hut',
    city: 'Stara Planina',
    country: 'Bulgaria',
    ...windy('1520936199'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/42.784N25.198E1177_Europe%2FSofia',
  },
  {
    id: 'bg-kalofer-windy',
    lat: 42.612,
    lng: 24.978,
    name: 'Kalofer',
    city: 'Kalofer',
    country: 'Bulgaria',
    ...windy('1602420354'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/42.784N25.198E1177_Europe%2FSofia',
  },
  {
    id: 'bg-kazanlak-windy',
    lat: 42.618,
    lng: 25.398,
    name: 'Kazanlak – Seuthopolis Square',
    city: 'Kazanlak',
    country: 'Bulgaria',
    ...windy('1520856341'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/42.784N25.198E1177_Europe%2FSofia',
  },
  {
    id: 'bg-tryavna-windy',
    lat: 42.872,
    lng: 25.502,
    name: 'Tryavna',
    city: 'Tryavna',
    country: 'Bulgaria',
    ...windy('1597690315'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/42.784N25.198E1177_Europe%2FSofia',
  },
  {
    id: 'bg-apriltsi-pleven-windy',
    lat: 42.836,
    lng: 24.918,
    name: 'Apriltsi – Pleven Hut',
    city: 'Apriltsi',
    country: 'Bulgaria',
    ...windy('1647535567'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/42.784N25.198E1177_Europe%2FSofia',
  },
  {
    id: 'bg-karlovo-windy',
    lat: 42.637,
    lng: 24.802,
    name: 'Karlovo',
    city: 'Karlovo',
    country: 'Bulgaria',
    ...windy('1677477742'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/42.784N25.198E1177_Europe%2FSofia',
  },
  {
    id: 'bg-pavel-banya-windy',
    lat: 42.602,
    lng: 25.198,
    name: 'Pavel Banya – South',
    city: 'Pavel Banya',
    country: 'Bulgaria',
    ...windy('1684264864'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/42.784N25.198E1177_Europe%2FSofia',
  },

  // ── weather-webcam.eu (meter.ac / home-solutions, probed live) ──
  {
    id: 'bg-nesebar-apolon',
    lat: 42.662,
    lng: 27.718,
    name: 'Nesebar – Apolon Complex',
    city: 'Nesebar',
    country: 'Bulgaria',
    feed_url: 'https://home-solutions.bg/cams/apolon.jpg',
    external_url: 'https://weather-webcam.eu/online-webcam-nesebar-apolon-cherno-more-black-sea/',
    source: 'home-solutions.bg / weather-webcam.eu',
  },
  {
    id: 'bg-plovdiv-center-meter',
    lat: 42.142,
    lng: 24.714,
    name: 'Plovdiv – Center (meter.ac)',
    city: 'Plovdiv',
    country: 'Bulgaria',
    feed_url: 'https://meter.ac/gs/nodes/N06/snap.jpg',
    external_url: 'https://weather-webcam.eu/plovdiv-centar-live-kamera/',
    source: 'meter.ac / weather-webcam.eu',
  },
  {
    id: 'bg-kavarna-bozhurets-meter',
    lat: 43.448,
    lng: 28.125,
    name: 'Kavarna – Bozhurets (meter.ac)',
    city: 'Kavarna',
    country: 'Bulgaria',
    feed_url: 'https://meter.ac/gs/nodes/N143/snap.jpg',
    external_url: 'https://weather-webcam.eu/bozhurets-kavarna-panorama-cherno-more-meteo-stancia-kamera-na-jivo/',
    source: 'meter.ac / weather-webcam.eu',
  },

  // ── BalticLiveCam (HLS via auth_token proxy; poster JPG fallback) ──
  {
    id: 'bg-blc-sunny-beach',
    lat: 42.695,
    lng: 27.71,
    name: 'Sunny Beach (Slanchev Bryag)',
    city: 'Nessebar',
    country: 'Bulgaria',
    stream_url: '/api/cctv/blc-stream?id=78630',
    stream_type: 'hls',
    feed_url: 'https://thumbs.balticlivecam.com/blc/p_BG_Burgas_Slanchev_Bryag.jpg',
    external_url: 'https://balticlivecam.com/cameras/bulgaria/burgas/slanchev-bryag/',
    source: 'BalticLiveCam / webcams.bg',
  },
  {
    id: 'bg-blc-kiten-urdoviza',
    lat: 42.234,
    lng: 27.775,
    name: 'Kiten – Urdoviza Beach',
    city: 'Kiten',
    country: 'Bulgaria',
    stream_url: '/api/cctv/blc-stream?id=21401',
    stream_type: 'hls',
    feed_url: 'https://thumbs.balticlivecam.com/blc/p_BG_Kiten_Urdoviza_beach.jpg',
    external_url: 'https://balticlivecam.com/cameras/bulgaria/kiten/urdoviza-beach/',
    source: 'BalticLiveCam',
  },
  {
    id: 'bg-blc-vidin-bdinci',
    lat: 43.989,
    lng: 22.873,
    name: 'Vidin – Bdinci Square',
    city: 'Vidin',
    country: 'Bulgaria',
    stream_url: '/api/cctv/blc-stream?id=48656',
    stream_type: 'hls',
    feed_url: 'https://thumbs.balticlivecam.com/blc/p_BG_Vidin_Bdinci_square.jpg',
    external_url: 'https://balticlivecam.com/cameras/bulgaria/vidin/bdinci-square/',
    source: 'BalticLiveCam',
  },
  {
    id: 'bg-blc-veliko-tarnovo',
    lat: 43.085,
    lng: 25.656,
    name: 'Veliko Tarnovo – Panorama',
    city: 'Veliko Tarnovo',
    country: 'Bulgaria',
    stream_url: '/api/cctv/blc-stream?id=88085',
    stream_type: 'hls',
    feed_url: 'https://thumbs.balticlivecam.com/blc/p_BG_Veliko_Tarnovo.jpg',
    external_url: 'https://balticlivecam.com/cameras/bulgaria/veliko-tarnovo/veliko-tarnovo-panoramic-view/',
    source: 'BalticLiveCam',
  },
];

function cameraKey(cam: CctvCamera): string {
  if (cam.stream_url?.includes('/api/cctv/blc-stream')) {
    return cam.stream_url;
  }
  return (cam.stream_url || cam.feed_url || cam.external_url || cam.id).split('?')[0];
}

export async function fetchBulgariaCameras(): Promise<CctvCamera[]> {
  const seen = new Set<string>();
  const merged: CctvCamera[] = [];

  for (const cam of [...BULGARIA_MANUAL, ...BULGARIA_FWCBG_CAMERAS]) {
    if (!cam.feed_url && !cam.stream_url && !cam.external_url) continue;
    const key = cameraKey(cam);
    if (seen.has(key)) continue;
    seen.add(key);
    merged.push(cam);
  }

  return filterHealthyBalkansCameras(merged);
}
