import type { CctvCamera } from './types';
import { windy } from './windy';

/** Northern Italy & Sardinia — Windy webcams via meteoblue (Milan, Verona, Cagliari, Olbia). */
const ITALY_CAMERAS: CctvCamera[] = [
  // ── Milan (meteoblue) ──
  {
    id: 'it-milan-duomo-windy',
    lat: 45.464,
    lng: 9.191,
    name: 'Milan – Duomo',
    city: 'Milan',
    country: 'Italy',
    ...windy('1170927034'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/milan_italy_3173435',
  },
  {
    id: 'it-milan-tre-torri-windy',
    lat: 45.478,
    lng: 9.154,
    name: 'Milan – Tre Torri / CityLife',
    city: 'Milan',
    country: 'Italy',
    ...windy('1641239368'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/milan_italy_3173435',
  },
  {
    id: 'it-milan-porta-nuova-windy',
    lat: 45.485,
    lng: 9.195,
    name: 'Milan – Porta Nuova / Bosco Verticale',
    city: 'Milan',
    country: 'Italy',
    ...windy('1532239794'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/milan_italy_3173435',
  },
  {
    id: 'it-milan-citylife-windy',
    lat: 45.478,
    lng: 9.159,
    name: 'Milan – CityLife Towers',
    city: 'Milan',
    country: 'Italy',
    ...windy('1556781642'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/milan_italy_3173435',
  },
  {
    id: 'it-milan-north-windy',
    lat: 45.51,
    lng: 9.18,
    name: 'Milan – North Panorama',
    city: 'Milan',
    country: 'Italy',
    ...windy('1607884670'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/milan_italy_3173435',
  },

  // ── Verona (meteoblue) ──
  {
    id: 'it-verona-center-windy',
    lat: 45.438,
    lng: 10.994,
    name: 'Verona – City Center',
    city: 'Verona',
    country: 'Italy',
    ...windy('1675295337'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/verona_italy_3164527',
  },
  {
    id: 'it-verona-east-windy',
    lat: 45.442,
    lng: 11.02,
    name: 'Verona – East',
    city: 'Verona',
    country: 'Italy',
    ...windy('1793884684'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/verona_italy_3164527',
  },
  {
    id: 'it-verona-west-windy',
    lat: 45.435,
    lng: 10.97,
    name: 'Verona – West',
    city: 'Verona',
    country: 'Italy',
    ...windy('1793898189'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/verona_italy_3164527',
  },

  // ── Sardinia – Cagliari (meteoblue) ──
  {
    id: 'it-cagliari-euclide-windy',
    lat: 39.22,
    lng: 9.115,
    name: 'Cagliari – Liceo Euclide',
    city: 'Cagliari',
    country: 'Italy',
    ...windy('1793901696'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/cagliari_italy_2525473',
  },
  {
    id: 'it-cagliari-poetto-east-windy',
    lat: 39.2,
    lng: 9.155,
    name: 'Cagliari – Poetto Beach (Gulf)',
    city: 'Cagliari',
    country: 'Italy',
    ...windy('1653032060'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/cagliari_italy_2525473',
  },
  {
    id: 'it-cagliari-poetto-windy',
    lat: 39.205,
    lng: 9.148,
    name: 'Cagliari – Poetto',
    city: 'Cagliari',
    country: 'Italy',
    ...windy('1620142180'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/cagliari_italy_2525473',
  },
  {
    id: 'it-cagliari-capoterra-windy',
    lat: 39.175,
    lng: 9.012,
    name: 'Capoterra – Beach',
    city: 'Capoterra',
    country: 'Italy',
    ...windy('1663855496'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/cagliari_italy_2525473',
  },

  // ── Sardinia – Olbia / Costa Smeralda (meteoblue) ──
  {
    id: 'it-olbia-center-windy',
    lat: 40.923,
    lng: 9.502,
    name: 'Olbia – City Center',
    city: 'Olbia',
    country: 'Italy',
    ...windy('1601618149'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/olbia_italy_3172087',
  },
  {
    id: 'it-olbia-port-windy',
    lat: 40.915,
    lng: 9.525,
    name: 'Olbia – Port Entrance',
    city: 'Olbia',
    country: 'Italy',
    ...windy('1691071259'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/olbia_italy_3172087',
  },
  {
    id: 'it-olbia-pittulongu-windy',
    lat: 40.915,
    lng: 9.545,
    name: 'Olbia – Pittulongu / Tavolara',
    city: 'Olbia',
    country: 'Italy',
    ...windy('1619732775'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/olbia_italy_3172087',
  },
  {
    id: 'it-olbia-le-saline-windy',
    lat: 40.908,
    lng: 9.55,
    name: 'Olbia – Le Saline Beach',
    city: 'Olbia',
    country: 'Italy',
    ...windy('1664460027'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/olbia_italy_3172087',
  },
  {
    id: 'it-olbia-tavolara-windy',
    lat: 40.895,
    lng: 9.62,
    name: 'Tavolara Island – Coast View',
    city: 'Olbia',
    country: 'Italy',
    ...windy('1404823490'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/olbia_italy_3172087',
  },
];

export async function fetchItalyCameras(): Promise<CctvCamera[]> {
  return ITALY_CAMERAS.filter((cam) => cam.feed_url || cam.stream_url || cam.external_url);
}
