import type { CctvCamera } from './types';

/** North Macedonia — Neotel HLS border and highway streams. */
const MACEDONIA_CAMERAS: CctvCamera[] = [
  {
    id: 'mk-deve-bair',
    lat: 42.149, lng: 22.537,
    name: 'Deve Bair – Gyueshevo Border',
    city: 'Deve Bair', country: 'North Macedonia',
    stream_url: 'https://streaming1.neotel.net.mk/stream/deve_bair.m3u8',
    stream_type: 'hls',
    external_url: 'https://www.weather-webcam.eu/cams/deve-bair.html',
    source: 'Neotel / GKPP',
  },
  {
    id: 'mk-tabanovce',
    lat: 42.232, lng: 21.718,
    name: 'Tabanovce – Preševo Border',
    city: 'Tabanovce', country: 'North Macedonia',
    stream_url: 'https://streaming1.neotel.net.mk/stream/tabanovce.m3u8',
    stream_type: 'hls',
    external_url: 'https://weather-webcam.eu/cams/tabanovce.html',
    source: 'Neotel / GKPP',
  },
  {
    id: 'mk-bogorodica',
    lat: 41.144, lng: 22.534,
    name: 'Bogorodica – Gevgelija Border',
    city: 'Bogorodica', country: 'North Macedonia',
    stream_url: 'https://streaming1.neotel.net.mk/stream/bogorodica.m3u8',
    stream_type: 'hls',
    external_url: 'https://www.weather-webcam.eu/cams/make-bogorodica.html',
    source: 'Neotel / GKPP',
  },
  {
    id: 'mk-miladinovci-1',
    lat: 42.212, lng: 21.745,
    name: 'Miladinovci Border (cam 1)',
    city: 'Miladinovci', country: 'North Macedonia',
    stream_url: 'https://streaming1.neotel.net.mk/stream/miladinovci_1.m3u8',
    stream_type: 'hls',
    external_url: 'https://www.weather-webcam.eu/cams/miladinovci_1.html',
    source: 'Neotel / GKPP',
  },
  {
    id: 'mk-miladinovci-2',
    lat: 42.211, lng: 21.747,
    name: 'Miladinovci Border (cam 2)',
    city: 'Miladinovci', country: 'North Macedonia',
    stream_url: 'https://streaming1.neotel.net.mk/stream/miladinovci_2.m3u8',
    stream_type: 'hls',
    external_url: 'https://www.weather-webcam.eu/cams/miladinovci_2.html',
    source: 'Neotel / GKPP',
  },
  {
    id: 'mk-medzitlija',
    lat: 40.936, lng: 21.415,
    name: 'Medžitlija – Bitola Border',
    city: 'Medžitlija', country: 'North Macedonia',
    stream_url: 'https://streaming1.neotel.net.mk/stream/medzitlija.m3u8',
    stream_type: 'hls',
    external_url: 'https://weather-webcam.eu/cams/medzitlija.html',
    source: 'Neotel / GKPP',
  },
  {
    id: 'mk-tetovo',
    lat: 42.01, lng: 20.971,
    name: 'Tetovo',
    city: 'Tetovo', country: 'North Macedonia',
    stream_url: 'https://streaming1.neotel.net.mk/stream/zelino_1.m3u8',
    stream_type: 'hls',
    external_url: 'https://weather-webcam.eu/cams/tetovo.html',
    source: 'Neotel',
  },
  {
    id: 'mk-veles',
    lat: 41.716, lng: 21.773,
    name: 'Veles Highway',
    city: 'Veles', country: 'North Macedonia',
    stream_url: 'https://streaming1.neotel.net.mk/stream/otovica_2.m3u8',
    stream_type: 'hls',
    external_url: 'https://weather-webcam.eu/cams/veles.html',
    source: 'Neotel',
  },
  {
    id: 'mk-skopje',
    lat: 41.998, lng: 21.431,
    name: 'Skopje – Millennium Cross Panorama',
    city: 'Skopje', country: 'North Macedonia',
    external_url: 'https://weather-webcam.eu/360-panoramna-ueb-kamera-ot-skopie-ot-mileniumski-krast-1000-m/',
    source: 'weather-webcam.eu',
  },
];

export async function fetchMacedoniaCameras(): Promise<CctvCamera[]> {
  return MACEDONIA_CAMERAS.filter((cam) => cam.feed_url || cam.stream_url || cam.external_url);
}
