import type { CctvCamera } from './types';
import { filterHealthyBalkansCameras } from './balkans-filter';
import { windy } from './windy';

/** Romanian webcams — cities, Black Sea coast, Danube border. */
const ROMANIA_CAMERAS: CctvCamera[] = [
  {
    id: 'ro-bucharest',
    lat: 44.426,
    lng: 26.102,
    name: 'Bucharest Panorama',
    city: 'Bucharest',
    country: 'Romania',
    feed_url: 'https://home-solutions.bg/cams/bukor.jpg',
    external_url: 'https://weather-webcam.eu/cam-camera-online-romania-bucharest-1/',
    source: 'home-solutions.bg',
  },
  {
    id: 'ro-bailesti',
    lat: 44.025,
    lng: 23.235,
    name: 'Băilești',
    city: 'Băilești',
    country: 'Romania',
    ...windy('1373238237'),
    external_url: 'https://weather-webcam.eu/cam-camera-online-romania-bailesti-live/',
  },
  {
    id: 'ro-brasov',
    lat: 45.657,
    lng: 25.601,
    name: 'Brașov',
    city: 'Brașov',
    country: 'Romania',
    external_url: 'https://weather-webcam.eu/cam-camera-online-romania-brashov/',
    source: 'weather-webcam.eu',
  },
  {
    id: 'ro-eforie-sud',
    lat: 44.058,
    lng: 28.632,
    name: 'Eforie Sud – Black Sea',
    city: 'Eforie Sud',
    country: 'Romania',
    stream_url: 'https://g0.ipcamlive.com/player/player.php?alias=5ad96539684a9&autoplay=1',
    stream_type: 'iframe',
    external_url: 'https://weather-webcam.eu/ueb-kamera-ot-eforie-sud/',
    source: 'IPCamLive',
  },
  {
    id: 'ro-giurgiu-bridge',
    lat: 43.903,
    lng: 25.974,
    name: 'Giurgiu – Ruse Danube Bridge',
    city: 'Giurgiu',
    country: 'Romania',
    feed_url: 'https://weather-webcam.eu/cams/gkpp-ruse-gurgevo-webcam-kamera-na-jivo.jpg',
    external_url: 'https://weather-webcam.eu/gkpp-ruse-gurgevo-dunav-most-bulgaria-romania-kamera-na-jivo-vremeto-dunav-onlain/',
    source: 'weather-webcam.eu',
  },
  {
    id: 'ro-giurgiu-bridge-2',
    lat: 43.902,
    lng: 25.976,
    name: 'Giurgiu – Danube Bridge (lane 2)',
    city: 'Giurgiu',
    country: 'Romania',
    feed_url: 'https://weather-webcam.eu/cams/gkpp-ruse-gurgevo-webcam-kamera-na-jivo2.jpg',
    source: 'weather-webcam.eu',
  },
  {
    id: 'ro-oltenita-tutrakan',
    lat: 44.093,
    lng: 26.636,
    name: 'Oltenița – Tutrakan Ferry',
    city: 'Oltenița',
    country: 'Romania',
    feed_url: 'https://weather-webcam.eu/cams/ruse-webcam-gkpp-kam-tutrakan.jpg',
    source: 'weather-webcam.eu',
  },
  {
    id: 'ro-balea-lake',
    lat: 45.604,
    lng: 24.616,
    name: 'Balea Lake – Carpathians',
    city: 'Sibiu',
    country: 'Romania',
    external_url: 'https://weather-webcam.eu/balea-lake-karpati-romania-live-kamera-vremeto-ski/',
    source: 'weather-webcam.eu',
  },

  // ── Constanța coast (meteoblue/Windy) ──
  {
    id: 'ro-constanta-port-windy',
    lat: 44.158,
    lng: 28.652,
    name: 'Constanța – Port',
    city: 'Constanța',
    country: 'Romania',
    ...windy('1627456589'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/constanta_romania_680963',
  },
  {
    id: 'ro-constanta-mamaia-windy',
    lat: 44.246,
    lng: 28.632,
    name: 'Constanța – Mamaia Cable Park',
    city: 'Constanța',
    country: 'Romania',
    ...windy('1793905807'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/constanta_romania_680963',
  },
  {
    id: 'ro-constanta-centru-windy',
    lat: 44.176,
    lng: 28.634,
    name: 'Constanța – City Center',
    city: 'Constanța',
    country: 'Romania',
    ...windy('1625390551'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/constanta_romania_680963',
  },
  {
    id: 'ro-constanta-zoom-beach-windy',
    lat: 44.152,
    lng: 28.638,
    name: 'Constanța – Zoom Beach',
    city: 'Constanța',
    country: 'Romania',
    ...windy('1793906291'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/constanta_romania_680963',
  },
  {
    id: 'ro-mangalia-marina-windy',
    lat: 43.802,
    lng: 28.582,
    name: 'Mangalia – Marina',
    city: 'Mangalia',
    country: 'Romania',
    ...windy('1793900531'),
    external_url: 'https://www.meteoblue.com/en/weather/webcams/constanta_romania_680963',
  },
];

export async function fetchRomaniaCameras(): Promise<CctvCamera[]> {
  return filterHealthyBalkansCameras(
    ROMANIA_CAMERAS.filter((cam) => cam.feed_url || cam.stream_url || cam.external_url),
  );
}
