import type { CctvCamera } from './types';

/** Curated Serbian webcams — border crossings, cities, resorts. */
const SERBIA_CAMERAS: CctvCamera[] = [
  {
    id: 'rs-belgrade-live',
    lat: 44.817,
    lng: 20.456,
    name: 'Belgrade Live Cam',
    city: 'Belgrade',
    country: 'Serbia',
    feed_url: 'https://stream.uzivobeograd.rs/live/cam_7.jpg',
    external_url: 'https://weather-webcam.eu/belgrad-webcam-online-na-jivo-kamera-ujivo-bg/',
    source: 'Uzivo Beograd',
  },
  {
    id: 'rs-kalotina-gradina-1',
    lat: 42.997,
    lng: 22.882,
    name: 'Kalotina – Gradina Border (lane 1)',
    city: 'Gradina',
    country: 'Serbia',
    external_url: 'https://www.weather-webcam.eu/cams/gradina1.html',
    source: 'AMSS / GKPP',
  },
  {
    id: 'rs-kalotina-gradina-2',
    lat: 42.996,
    lng: 22.884,
    name: 'Kalotina – Gradina Border (lane 2)',
    city: 'Gradina',
    country: 'Serbia',
    external_url: 'https://www.weather-webcam.eu/cams/gradina2.html',
    source: 'AMSS / GKPP',
  },
  {
    id: 'rs-zlatibor',
    lat: 43.729,
    lng: 19.713,
    name: 'Zlatibor Mountain',
    city: 'Zlatibor',
    country: 'Serbia',
    feed_url: 'https://radionicakrug.com/kamera/zlatiborrs.jpg',
    external_url: 'https://weather-webcam.eu/online-live-webcam-weather-zlatibor-sarbia/',
    source: 'Radionica Krug',
  },
  {
    id: 'rs-senta',
    lat: 45.927,
    lng: 20.078,
    name: 'Senta',
    city: 'Senta',
    country: 'Serbia',
    feed_url: 'https://home-solutions.bg/cams/senta.jpg',
    external_url: 'https://weather-webcam.eu/senta-serbia-webcam-online-na-jivo-kamera-ujivo/',
    source: 'home-solutions.bg',
  },
  {
    id: 'rs-subotica',
    lat: 46.1,
    lng: 19.665,
    name: 'Subotica',
    city: 'Subotica',
    country: 'Serbia',
    external_url: 'https://weather-webcam.eu/webcam-sarbia-subotica/',
    source: 'weather-webcam.eu',
  },
  {
    id: 'rs-zrenjanin',
    lat: 45.383,
    lng: 20.381,
    name: 'Zrenjanin',
    city: 'Zrenjanin',
    country: 'Serbia',
    external_url: 'https://weather-webcam.eu/online-webcam-zrenianin-sarbia-na-zivo/',
    source: 'weather-webcam.eu',
  },
  {
    id: 'rs-kopaonik',
    lat: 43.285,
    lng: 20.816,
    name: 'Kopaonik Ski Resort',
    city: 'Kopaonik',
    country: 'Serbia',
    external_url: 'https://weather-webcam.eu/kopaonik-webcam-online-na-jivo-kamera-ujivo/',
    source: 'weather-webcam.eu',
  },
];

export async function fetchSerbiaCameras(): Promise<CctvCamera[]> {
  return SERBIA_CAMERAS.filter((cam) => cam.feed_url || cam.external_url);
}
